// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lookaside.proto

/*
Package _proto is a generated protocol buffer package.

It is generated from these files:
	lookaside.proto

It has these top-level messages:
	Request
	Response
*/
package _proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_RouterType int32

const (
	Request_RANDOM     Request_RouterType = 0
	Request_ROUNDROBIN Request_RouterType = 1
)

var Request_RouterType_name = map[int32]string{
	0: "RANDOM",
	1: "ROUNDROBIN",
}
var Request_RouterType_value = map[string]int32{
	"RANDOM":     0,
	"ROUNDROBIN": 1,
}

func (x Request_RouterType) String() string {
	return proto.EnumName(Request_RouterType_name, int32(x))
}
func (Request_RouterType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Request struct {
	Service string             `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Router  Request_RouterType `protobuf:"varint,2,opt,name=router,enum=_proto.Request_RouterType" json:"router,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Request) GetRouter() Request_RouterType {
	if m != nil {
		return m.Router
	}
	return Request_RANDOM
}

type Response struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "_proto.Request")
	proto.RegisterType((*Response)(nil), "_proto.Response")
	proto.RegisterEnum("_proto.Request_RouterType", Request_RouterType_name, Request_RouterType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Lookaside service

type LookasideClient interface {
	Resolve(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type lookasideClient struct {
	cc *grpc.ClientConn
}

func NewLookasideClient(cc *grpc.ClientConn) LookasideClient {
	return &lookasideClient{cc}
}

func (c *lookasideClient) Resolve(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/_proto.Lookaside/Resolve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Lookaside service

type LookasideServer interface {
	Resolve(context.Context, *Request) (*Response, error)
}

func RegisterLookasideServer(s *grpc.Server, srv LookasideServer) {
	s.RegisterService(&_Lookaside_serviceDesc, srv)
}

func _Lookaside_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookasideServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/_proto.Lookaside/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookasideServer).Resolve(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lookaside_serviceDesc = grpc.ServiceDesc{
	ServiceName: "_proto.Lookaside",
	HandlerType: (*LookasideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Lookaside_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lookaside.proto",
}

func init() { proto.RegisterFile("lookaside.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xbf, 0x6b, 0x86, 0x30,
	0x10, 0x86, 0x4d, 0x87, 0x58, 0x6f, 0x50, 0xc9, 0x24, 0x4e, 0x12, 0x3a, 0x38, 0x65, 0xb0, 0x63,
	0xa7, 0x16, 0x97, 0x42, 0xab, 0x70, 0xb4, 0x73, 0xb1, 0xf5, 0x06, 0xa9, 0x34, 0x36, 0xa7, 0x42,
	0xc7, 0xfe, 0xe7, 0x1f, 0xfe, 0x42, 0xf8, 0xa6, 0xf0, 0x3e, 0xb9, 0xf7, 0x78, 0x0e, 0xa2, 0xde,
	0xda, 0xef, 0x86, 0xbb, 0x96, 0xcc, 0xe0, 0xec, 0x68, 0x95, 0xfc, 0x58, 0x5f, 0xfd, 0x2f, 0xc0,
	0x47, 0xfa, 0x9d, 0x88, 0x47, 0x95, 0x80, 0xcf, 0xe4, 0xe6, 0xee, 0x8b, 0x12, 0x91, 0x89, 0x3c,
	0xc0, 0x23, 0xaa, 0x02, 0xa4, 0xb3, 0xd3, 0x48, 0x2e, 0xb9, 0xc9, 0x44, 0x1e, 0x16, 0xa9, 0xd9,
	0xea, 0x66, 0xaf, 0x1a, 0x5c, 0x7f, 0xdf, 0xfe, 0x06, 0xc2, 0x7d, 0x52, 0xe7, 0x00, 0x27, 0x55,
	0x00, 0x12, 0x1f, 0xab, 0xb2, 0x7e, 0x8d, 0x3d, 0x15, 0x02, 0x60, 0xfd, 0x5e, 0x95, 0x58, 0x3f,
	0x3d, 0x57, 0xb1, 0xd0, 0x77, 0x70, 0x8b, 0xc4, 0x83, 0xfd, 0x61, 0x5a, 0x1c, 0x9a, 0xb6, 0x75,
	0xc4, 0x7c, 0x38, 0xec, 0xb1, 0x78, 0x80, 0xe0, 0xe5, 0x38, 0x42, 0x99, 0xc5, 0x9a, 0x6d, 0x3f,
	0x93, 0x8a, 0xae, 0x5c, 0xd2, 0xf8, 0x04, 0xdb, 0x52, 0xed, 0x7d, 0xca, 0x95, 0xdc, 0x5f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xb2, 0x3f, 0x09, 0x83, 0x08, 0x01, 0x00, 0x00,
}
